{% set version = "2020.9.27" %}

package:
  name: regex
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/regex/regex-{{ version }}.tar.gz
  sha256: a6f32aea4260dfe0e55dc9733ea162ea38f0ea86aa7d0f77b15beac5bf7b369d

build:
  number: 1
  skip: true  # [win and py27]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - regex

about:
  home: https://bitbucket.org/mrabarnett/mrab-regex
  # https://bitbucket.org/mrabarnett/mrab-regex/issues/124/please-add-a-license-file-to-the-package
  license: Python-2.0
  license_family: PSF
  summary: Alternative regular expression module, to replace re

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
    - xhochy
